version: '3'

networks:
  mynetwork:
    driver: bridge

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
            device: /home/$USER/data/wordpress
            o: bind
            type: none
  database:
    name: database
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirement/mariadb/
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

  wordpress:
    container_name: wordpress
    build:
       context: ./requirement/wordpress/  # Change to the actual path
    depends_on:
      - mariadb
#      - redis
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirement/nginx/ # Change to the actual path
    depends_on:
      - wordpress
    ports:
      - "443:443"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always
#############################################
##################bonus######################
#############################################
  redis:
    container_name: redis
    build:
      context: ./requirement/bonus/redis/.
    image: redis
    volumes:
     - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

  ftp:
    container_name: ftp
    build: ./requirement/bonus/ftp/.
    image: ftp:42
    depends_on:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - mynetwork
    restart: always
#################
  adminer:
    container_name: adminer
    build: ./requirement/bonus/adminer/.
    image: adminer
    ports:
      - "800:800"
    depends_on:
      - mariadb
    # volumes:
    #   - wordpress-data:/var/www/html
    networks:
      - mynetwork
    restart: always

##################3
  static_page:
    container_name: static_page
    build:
       context: ./requirement/bonus/static_page/  # Change to the actual path
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always
  # adminer:
  #   image: dockette/adminer:full-php5
  #   restart: always
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   networks:
  #     - mynetwork
  #   ports:
  #       - 8080:8080

  # ftp-server:
  #   container_name: ftp-server
  #   build: 
  #     context: ./requirement/bonus/ftp
  #   ports:
  #     - "21:21"
  #     - "21100-21110:21100-21110"
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   networks:
  #     - mynetwork
  #   env_file:
  #     - ./.env
  #   restart: always
