version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirement/mariadb/
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

  wordpress:
    container_name: wordpress
    build:
       context: ./requirement/wordpress/  # Change to the actual path
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirement/nginx/ # Change to the actual path
    depends_on:
      - wordpress
    ports:
      - "443:443"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - mynetwork
    env_file:
      - ./.env
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
            device: /home/$USER/data/wordpress
            o: bind
            type: none
  database:
    name: database
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none
