version: '3'

networks:
  mynetwork:
    driver: bridge

volumes:
  wordpress-dat:
    name: wordpress-dat
    driver: local
    driver_opts:
            device: /home/$USER/data/wordpress
            o: bind
            type: none
  databas:
    name: databas
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

services:
  mariadb:
    build:
      context: requirements/mariadb/
    container_name: mariadb
    networks:
      - mynetwork
    volumes:
      - databas:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env
    restart:
      always
  
  wordpress:
    build: 
      context: requirements/wordpress/
    container_name: wordpress
    networks:
      - mynetwork
    expose:
      - 9000
    volumes:
      - wordpress-dat:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart:
      always
    
  nginx:
    build: 
      context: requirements/nginx/
    container_name: nginx
    networks:
      - mynetwork
    ports:
      - 443:443
    volumes:
      - wordpress-dat:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart:
      always
    
#############bonus##############

  redis:
    build: 
      context: requirements/bonus/redis/
    container_name: redis
    networks:
      - mynetwork
    ports:
      - 6379:6379
    volumes:
      - wordpress-dat:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart:
      always
    
  adminer:
    build: 
      context: requirements/bonus/adminer
    container_name: adminer
    networks:
      - mynetwork
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  ftp:
    build: 
      context: requirements/bonus/ftp
    container_name: ftp
    networks:
      - mynetwork
    volumes:
      - wordpress-dat:/var/ftp
    ports:
      - 21:21
      - 30000-30009:30000-30009
    depends_on:
      - wordpress
    env_file:
      - .env
    restart : always

  cadvisor:
    build: 
      context: requirements/bonus/cadvisor
    container_name: cadvisor
    networks:
      - mynetwork
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 808:808
    env_file:
      - .env
    restart : always
    
  static_page:
    build: 
      context: requirements/bonus/static_page
    container_name: static_page
    networks:
      - mynetwork
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always

    